<?php

class StudentProjectsTableSeeder extends Seeder{

	public function run()
	{
		$nu = new Datetime();

		$studentProjects = [
			["project" => 3,
			"leerling" => 6,
			"docent" => 1,
			"begin_datum" => "2014-01-13",
			"deadline" => "2014-04-01",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 5,
			"leerling" => 7,
			"docent" => 1,
			"begin_datum" => "2014-01-15",
			"deadline" => "2014-04-03",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 3,
			"leerling" => 2,
			"docent" => 3,
			"begin_datum" => "2014-01-22",
			"deadline" => "2014-04-08",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 2,
			"leerling" => 4,
			"docent" => 1,
			"begin_datum" => "2014-02-03",
			"deadline" => "2014-04-10",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 1,
			"leerling" => 4,
			"docent" => 3,
			"begin_datum" => "2014-02-12",
			"deadline" => "2014-04-11",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 4,
			"leerling" => 6,
			"docent" => 2,
			"begin_datum" => "2014-02-18",
			"deadline" => "2014-04-16",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 1,
			"leerling" => 1,
			"docent" => 1,
			"begin_datum" => "2014-02-19",
			"deadline" => "2014-04-17",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 5,
			"leerling" => 4,
			"docent" => 1,
			"begin_datum" => "2014-02-21",
			"deadline" => "2014-04-18",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 4,
			"leerling" => 2,
			"docent" => 1,
			"begin_datum" => "2014-02-28",
			"deadline" => "2014-04-24",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 1,
			"leerling" => 3,
			"docent" => 2,
			"begin_datum" => "2014-03-10",
			"deadline" => "2014-04-28",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 3,
			"leerling" => 6,
			"docent" => 2,
			"begin_datum" => "2014-03-18",
			"deadline" => "2014-05-05",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 3,
			"leerling" => 6,
			"docent" => 1,
			"begin_datum" => "2014-03-27",
			"deadline" => "2014-05-13",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 5,
			"leerling" => 5,
			"docent" => 3,
			"begin_datum" => "2014-03-31",
			"deadline" => "2014-05-19",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 3,
			"leerling" => 2,
			"docent" => 2,
			"begin_datum" => "2014-04-09",
			"deadline" => "2014-05-21",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 4,
			"leerling" => 6,
			"docent" => 3,
			"begin_datum" => "2014-04-11",
			"deadline" => "2014-05-30",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 2,
			"leerling" => 2,
			"docent" => 2,
			"begin_datum" => "2014-04-15",
			"deadline" => "2014-06-02",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 5,
			"leerling" => 6,
			"docent" => 3,
			"begin_datum" => "2014-04-23",
			"deadline" => "2014-06-23",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 4,
			"leerling" => 4,
			"docent" => 1,
			"begin_datum" => "2014-04-25",
			"deadline" => "2014-07-03",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 2,
			"leerling" => 6,
			"docent" => 1,
			"begin_datum" => "2014-04-30",
			"deadline" => "2014-07-04",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 5,
			"leerling" => 7,
			"docent" => 3,
			"begin_datum" => "2014-05-15",
			"deadline" => "2014-07-14",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 4,
			"leerling" => 4,
			"docent" => 3,
			"begin_datum" => "2014-05-16",
			"deadline" => "2014-07-15",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 1,
			"leerling" => 6,
			"docent" => 3,
			"begin_datum" => "2014-05-19",
			"deadline" => "2014-07-23",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 3,
			"leerling" => 5,
			"docent" => 3,
			"begin_datum" => "2014-05-22",
			"deadline" => "2014-07-28",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 3,
			"leerling" => 6,
			"docent" => 3,
			"begin_datum" => "2014-05-26",
			"deadline" => "2014-07-29",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 3,
			"leerling" => 3,
			"docent" => 1,
			"begin_datum" => "2014-05-30",
			"deadline" => "2014-07-30",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 4,
			"leerling" => 1,
			"docent" => 1,
			"begin_datum" => "2014-01-20",
			"deadline" => "2014-04-01",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 4,
			"leerling" => 2,
			"docent" => 2,
			"begin_datum" => "2014-01-22",
			"deadline" => "2014-04-03",
			"beoordelingsdatum" => null,
			"beoordeling" => null,
			"commentaar" => "",
			"created_at" => $nu],

			["project" => 5,
			"leerling" => 7,
			"docent" => 1,
			"begin_datum" => "2014-01-24",
			"deadline" => "2014-04-08",
			"beoordelingsdatum" => "2014-02-14",
			"beoordeling" => 3,
			"commentaar" => "Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen.",
			"created_at" => $nu],

			["project" => 4,
			"leerling" => 4,
			"docent" => 2,
			"begin_datum" => "2014-02-03",
			"deadline" => "2014-04-11",
			"beoordelingsdatum" => "2014-03-03",
			"beoordeling" => 3,
			"commentaar" => "Lorem Ipsum is de standaard proeftekst in deze bedrijfstak sinds de 16e eeuw, toen een onbekende drukker een zethaak met letters nam en ze door elkaar husselde om een font catalogus te maken.",
			 "created_at" => $nu],

			["project" => 2,
			"leerling" => 1,
			"docent" => 3,
			"begin_datum" => "2014-02-06",
			"deadline" => "2014-04-14",
			"beoordelingsdatum" => "2014-04-06",
			"beoordeling" => 2,
			"commentaar" => "Het heeft niet alleen vijf eeuwen overleefd maar is ook, vrijwel onveranderd, overgenomen in elektronische letterzetting.",
			 "created_at" => $nu],

			["project" => 5,
			"leerling" => 5,
			"docent" => 1,
			"begin_datum" => "2014-02-13",
			"deadline" => "2014-04-15",
			"beoordelingsdatum" => "2014-02-29",
			"beoordeling" => 2,
			"commentaar" => "Het is in de jaren '60 populair geworden met de introductie van Letraset vellen met Lorem Ipsum passages en meer recentelijk door desktop publishing software zoals Aldus PageMaker die versies van Lorem Ipsum bevatten.",
			"created_at" => $nu],

			["project" => 1,
			"leerling" => 7,
			"docent" => 2,
			"begin_datum" => "2014-02-19",
			"deadline" => "2014-04-17",
			"beoordelingsdatum" => "2014-04-19",
			"beoordeling" => 1,
			"commentaar" => "In tegenstelling tot wat algemeen aangenomen wordt is Lorem Ipsum niet zomaar willekeurige tekst.",
			"created_at" => $nu],

			["project" => 2,
			"leerling" => 3,
			"docent" => 3,
			"begin_datum" => "2014-02-24",
			"deadline" => "2014-04-28",
			"beoordelingsdatum" => "2014-03-24",
			"beoordeling" => 1,
			"commentaar" => "het heeft zijn wortels in een stuk klassieke latijnse literatuur uit 45 v.Chr. en is dus meer dan 2000 jaar oud.",
			"created_at" => $nu],

			["project" => 2,
			"leerling" => 2,
			"docent" => 3,
			"begin_datum" => "2014-03-11",
			"deadline" => "2014-04-29",
			"beoordelingsdatum" => "2014-05-11",
			"beoordeling" => 3,
			"commentaar" => "Richard McClintock, een professor latijn aan de Hampden-Sydney College in Virginia, heeft één van de meer obscure latijnse woorden, consectetur, uit een Lorem Ipsum passage opgezocht",
			 "created_at" => $nu],

			["project" => 2,
			"leerling" => 4,
			"docent" => 2,
			"begin_datum" => "2014-03-12",
			"deadline" => "2014-05-15",
			"beoordelingsdatum" => "2014-06-05",
			"beoordeling" => 1,
			"commentaar" => "en heeft tijdens het zoeken naar het woord in de klassieke literatuur de onverdachte bron ontdekt. Lorem Ipsum komt uit de secties 1.10.32 en 1.10.33 van ",
			"created_at" => $nu],

			["project" => 2,
			"leerling" => 2,
			"docent" => 1,
			"begin_datum" => "2014-03-13",
			"deadline" => "2014-05-19",
			"beoordelingsdatum" => "2014-07-13",
			"beoordeling" => 1,
			"commentaar" => "De uitersten van goed en kwaad) door Cicero, geschreven in 45 v.Chr. Dit boek is een verhandeling over de theorie der ethiek, erg populair tijdens de renaissance.",
			 "created_at" => $nu],

			["project" => 3,
			"leerling" => 1,
			"docent" => 2,
			"begin_datum" => "2014-03-19",
			"deadline" => "2014-05-21",
			"beoordelingsdatum" => "2014-06-19",
			"beoordeling" => 1,
			"commentaar" => "De eerste regel van Lorem Ipsum",
			 "created_at" => $nu],

			["project" => 3,
			"leerling" => 4,
			"docent" => 1,
			"begin_datum" => "2014-03-28",
			"deadline" => "2014-05-26",
			"beoordelingsdatum" => "2014-04-28",
			"beoordeling" => 3,
			"commentaar" => "Het standaard stuk van Lorum Ipsum wat sinds de 16e eeuw wordt gebruikt is hieronder, voor wie er interesse in heeft, weergegeven. ",
			 "created_at" => $nu],

			["project" => 2,
			"leerling" => 3,
			"docent" => 2,
			"begin_datum" => "2014-04-02",
			"deadline" => "2014-05-27",
			"beoordelingsdatum" => "2014-05-25",
			"beoordeling" => 1,
			"commentaar" => "Secties 1.10.32 en 1.10.33 van ",
			"created_at" => $nu],

			["project" => 3,
			"leerling" => 1,
			"docent" => 1,
			"begin_datum" => "2014-04-15",
			"deadline" => "2014-06-10",
			"beoordelingsdatum" => "2014-04-30",
			"beoordeling" => 1,
			"commentaar" => "vergezeld van engelse versies van de 1914 vertaling door H. Rackham.",
			"created_at" => $nu],

			["project" => 3,
			"leerling" => 6,
			"docent" => 3,
			"begin_datum" => "2014-04-16",
			"deadline" => "2014-06-11",
			"beoordelingsdatum" => "2014-05-29",
			"beoordeling" => 3,
			"commentaar" => "Het is al geruime tijd een bekend gegeven dat een lezer, tijdens het bekijken van de layout van een pagina, afgeleid wordt door de tekstuele inhoud.",
			 "created_at" => $nu],

			["project" => 5,
			"leerling" => 1,
			"docent" => 3,
			"begin_datum" => "2014-04-18",
			"deadline" => "2014-06-19",
			"beoordelingsdatum" => "2014-06-18",
			"beoordeling" => 1,
			"commentaar" => "Het belangrijke punt van het gebruik van Lorem Ipsum is dat het uit een min of meer normale verdeling van letters bestaat,
			",
			"created_at" => $nu],

			["project" => 3,
			"leerling" => 4,
			"docent" => 3,
			"begin_datum" => "2014-04-23",
			"deadline" => "2014-06-23",
			"beoordelingsdatum" => "2014-06-23",
			"beoordeling" => 3,
			"commentaar" => "in tegenstelling tot ",
			"created_at" => $nu],

			["project" => 2,
			"leerling" => 5,
			"docent" => 3,
			"begin_datum" => "2014-04-25",
			"deadline" => "2014-06-26",
			"beoordelingsdatum" => "2014-05-30",
			"beoordeling" => 1,
			"commentaar" => "Veel desktop publishing pakketten en web pagina editors gebruiken tegenwoordig Lorem Ipsum als hun standaard model tekst",
			"created_at" => $nu],

			["project" => 3,
			"leerling" => 3,
			"docent" => 3,
			"begin_datum" => "2014-04-28",
			"deadline" => "2014-07-03",
			"beoordelingsdatum" => "2014-06-04",
			"beoordeling" => 3,
			"commentaar" => "en een zoekopdracht naar ",
			"created_at" => $nu],

			["project" => 5,
			"leerling" => 7,
			"docent" => 2,
			"begin_datum" => "2014-04-29",
			"deadline" => "2014-07-08",
			"beoordelingsdatum" => "2014-06-29",
			"beoordeling" => 2,
			"commentaar" => "Verscheidene versies hebben zich ontwikkeld in de loop van de jaren",
			"created_at" => $nu],

			["project" => 2,
			"leerling" => 6,
			"docent" => 1,
			"begin_datum" => "2014-05-06",
			"deadline" => "2014-07-15",
			"beoordelingsdatum" => "2014-05-26",
			"beoordeling" => 3,
			"commentaar" => "soms per ongeluk soms expres (ingevoegde humor en dergelijke).",
			"created_at" => $nu],

			["project" => 4,
			"leerling" => 2,
			"docent" => 1,
			"begin_datum" => "2014-05-08",
			"deadline" => "2014-07-16",
			"beoordelingsdatum" => "2014-06-08",
			"beoordeling" => 2,
			"commentaar" => "Er zijn vele variaties van passages van Lorem Ipsum beschikbaar ",
			"created_at" => $nu],

			["project" => 5,
			"leerling" => 5,
			"docent" => 1,
			"begin_datum" => "2014-05-21",
			"deadline" => "2014-07-21",
			"beoordelingsdatum" => "2014-06-30",
			"beoordeling" => 3,
			"commentaar" => "maar het merendeel heeft te lijden gehad van wijzigingen in een of andere vorm",
			"created_at" => $nu],

			["project" => 4,
			"leerling" => 4,
			"docent" => 2,
			"begin_datum" => "2014-05-27",
			"deadline" => "2014-07-24",
			"beoordelingsdatum" => "2014-06-27",
			"beoordeling" => 3,
			"commentaar" => "door ingevoegde humor of willekeurig gekozen woorden die nog niet half geloofwaardig ogen",
			"created_at" => $nu]
		];

		DB::table('student_projects')->insert($studentProjects);
	}

}